### ISSUE TITLE
No example ./data 

### ISSUE THREAD

**Issue by julievdh** [dsholes/python-srs#1]
A demo data file (1.txt) stored in ./data/ would be very helpful in recreating the ipython notebook.

**Comment by dsholes** [comment]
That would have been a good idea. Unfortunately I don't have access to accelerometer data anymore. The expected data shape is described in the [read_tsv](https://github.com/dsholes/python-srs/blob/master/srspy/srs.py#L34-L38) function and [read_csv](https://github.com/dsholes/python-srs/blob/master/srspy/srs.py#L54-L62) function:

```
NOTE ON DATA FORMAT:
        - TSV must be 2 columns
            - Time (in sec) is first column
            - Accel (in G's) is second column
        - No column headers (i.e. first row should be data)
```
